/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Covid19;

import java.awt.Color;
import java.util.*;
import javax.swing.JOptionPane;
import Covid19.AdminstratorForm;
import static Covid19.AdminstratorForm.adminList;
import static Covid19.AdminstratorForm.jTableA1;
import static Covid19.AdminstratorForm.jTableA2;
import static Covid19.AdminstratorForm.jTableA3;
import static Covid19.AppointmentForm.jATable;
import static Covid19.RecipientForm.infoBox;
import static Covid19.RecipientForm.jRTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admin
 */
public class ClinicianForm extends javax.swing.JFrame {

    /**
     * Creates new form Clinician
     */
    public ClinicianForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jVC1 = new javax.swing.JTextField();
        jVC3 = new javax.swing.JTextField();
        jVC2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCID = new javax.swing.JTextField();
        jCName = new javax.swing.JTextField();
        jUD = new javax.swing.JButton();
        jDA = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCTable = new javax.swing.JTable();
        jRM = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel1.setText("Clinician");

        jLabel2.setText("Clinician ID:");

        jLabel3.setText("Clinician Name:");

        jLabel4.setText("Vaccine Invertory:");

        jLabel5.setText("Pfizer-BioNTech");
        jLabel5.setToolTipText("");

        jLabel6.setText("Moderna");

        jLabel7.setText("Johnson & Johnson’s Janssen");

        jVC1.setPreferredSize(new java.awt.Dimension(20, 20));

        jVC3.setPreferredSize(new java.awt.Dimension(20, 20));
        jVC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVC3ActionPerformed(evt);
            }
        });

        jVC2.setPreferredSize(new java.awt.Dimension(20, 20));

        jLabel8.setText(" Vaccine Name");

        jLabel9.setText("Amount");

        jCID.setEditable(false);
        jCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCIDActionPerformed(evt);
            }
        });

        jCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNameActionPerformed(evt);
            }
        });

        jUD.setText("UPDATE");
        jUD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUDActionPerformed(evt);
            }
        });

        jDA.setText("Display All");
        jDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDAActionPerformed(evt);
            }
        });

        jAdd.setText("ADD");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jB.setText("BACK");
        jB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActionPerformed(evt);
            }
        });

        jCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Clician ID", "Full Name", "Pfizer-BioNTech", "Moderna", "Johnson & Johnson's Janssen", "Total"
            }
        ));
        jCTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCTable);

        jRM.setText("REMOVE");
        jRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRMActionPerformed(evt);
            }
        });

        jLabel10.setText("Total");

        jTotal.setEditable(false);
        jTotal.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.MAGENTA);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(426, 426, 426)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(326, 326, 326))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addGap(188, 188, 188))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(121, 121, 121)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jVC2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jVC3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jVC1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCName, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jUD, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jRM)
                                .addGap(32, 32, 32)
                                .addComponent(jDA))
                            .addComponent(jB))))
                .addGap(26, 26, 26))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jAdd, jB, jDA, jRM, jUD});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jVC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jVC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jVC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jB)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUDActionPerformed
      if (adminList.CList.size()==0||jCName.getText().equals("")|| jVC1.getText().equals("")||jVC2.getText().equals("")||jVC3.getText().equals("")||jTotal.getText().equals(""))
        infoBox("Please filling out your information", "Missing data");
       else{
                    totalDose =   Integer.parseInt(jVC1.getText())+Integer.parseInt(jVC2.getText())+Integer.parseInt(jVC3.getText());
                jTotal.setText(String.valueOf(totalDose));
       adminList.CList.updateClinician(jCID.getText(),jCID.getText(), jCName.getText(), jVC1.getText(),jVC2.getText(),jVC3.getText(),jTotal.getText());
       adminList.CList.display();
    }
    }//GEN-LAST:event_jUDActionPerformed
    
    private void jCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCNameActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        
        if (jCName.getText().equals("")|| jVC1.getText().equals("")||jVC2.getText().equals("")||jVC3.getText().equals(""))
        infoBox("Please filling out your information", "Missing data");
        else
        {
            totalDose =   Integer.parseInt(jVC1.getText())+Integer.parseInt(jVC2.getText())+Integer.parseInt(jVC3.getText());
 jTotal.setText(String.valueOf(totalDose));
        DefaultTableModel model = (DefaultTableModel)jCTable.getModel();
        if (model.getRowCount()>0){   
        int  tempNum = Integer.parseInt(model.getValueAt(model.getRowCount()-1, 0).toString().substring(1));
          
        adminList.clinicianIdNum=tempNum+1;
        }
        else
        adminList.clinicianIdNum++;
        adminList.CList.addClinician("C"+String.valueOf(adminList.clinicianIdNum), jCName.getText(), jVC1.getText(),jVC2.getText(),jVC3.getText(),jTotal.getText());
        adminList.CList.display();
        clearTable2();
        }
       
    }                                    
     
        private void clearTable2(){
        jCID.setText("");
        jCName.setText("");
        jVC1.setText("");
        jVC2.setText("");
        jVC3.setText("");
        jTotal.setText("");

    }//GEN-LAST:event_jAddActionPerformed

    private void jBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActionPerformed
     this.setVisible(false);
   new AdminstratorForm().setVisible(true);
   new AdminstratorForm().setState(java.awt.Frame.NORMAL);   
    }//GEN-LAST:event_jBActionPerformed

    private void jCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCIDActionPerformed

    private void jDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDAActionPerformed
      
        adminList.CList.display();
    }//GEN-LAST:event_jDAActionPerformed

    private void jRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRMActionPerformed
       if (adminList.CList.size()==0)
           infoBox("Please filling out your information", "Missing data");
       else 
       {
        adminList.CList.removeClinician(jCID.getText());
     adminList.CList.display();
       clearTable2();}
           
    }//GEN-LAST:event_jRMActionPerformed

    private void jCTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCTableMouseClicked
DefaultTableModel model = (DefaultTableModel) jCTable.getModel();
       int selectedRowIndex = jCTable.getSelectedRow();
       jCID.setText(model.getValueAt(selectedRowIndex,0).toString());
       jCName.setText(model.getValueAt(selectedRowIndex,1).toString());
       jVC1.setText(model.getValueAt(selectedRowIndex,2).toString());
       jVC2.setText(model.getValueAt(selectedRowIndex,3).toString());   
       jVC3.setText(model.getValueAt(selectedRowIndex,4).toString());
       jTotal.setText(model.getValueAt(selectedRowIndex,5).toString());     
    }//GEN-LAST:event_jCTableMouseClicked

    private void jVC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVC3ActionPerformed
 
    }//GEN-LAST:event_jVC3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          adminList.CList.display();
    }//GEN-LAST:event_formWindowOpened
    public static void infoBox(String infoMessage, String titleBar)
    {   
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicianForm().setVisible(true);
            }
        });
    }
    private static int clinicianIdNum;
    private int totalDose=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jB;
    private javax.swing.JTextField jCID;
    private javax.swing.JTextField jCName;
    public static javax.swing.JTable jCTable;
    private javax.swing.JButton jDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jRM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JButton jUD;
    private javax.swing.JTextField jVC1;
    private javax.swing.JTextField jVC2;
    private javax.swing.JTextField jVC3;
    // End of variables declaration//GEN-END:variables
}
