/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Covid19;
import java.awt.Color;
//import java.util.*;
import javax.swing.JOptionPane;
//import Covid19.AdminstratorForm;
//import Covid19.AdminstratorForm;
import static Covid19.AdminstratorForm.adminList;
/*
import static Covid19.AdminstratorForm.jTableA1;
import static Covid19.AdminstratorForm.jTableA2;
import static Covid19.AdminstratorForm.jTableA3;
import static Covid19.AppointmentForm.jATable;
import static Covid19.ClinicianForm.jCTable;
*/
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */

public class RecipientForm extends javax.swing.JFrame {

   

   
    /**
     * Creates new form VaccineRecipient
         public VaccineRecipientForm() {*/
public RecipientForm(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jQY1 = new javax.swing.JCheckBox();
        jQY2 = new javax.swing.JCheckBox();
        jQY3 = new javax.swing.JCheckBox();
        jQY4 = new javax.swing.JCheckBox();
        jQY5 = new javax.swing.JCheckBox();
        jQY6 = new javax.swing.JCheckBox();
        jQN1 = new javax.swing.JCheckBox();
        jQN2 = new javax.swing.JCheckBox();
        jQN3 = new javax.swing.JCheckBox();
        jQN4 = new javax.swing.JCheckBox();
        jQN5 = new javax.swing.JCheckBox();
        jQN6 = new javax.swing.JCheckBox();
        jRecepientID = new javax.swing.JTextField();
        jFullName = new javax.swing.JTextField();
        jDateBirth = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jMale = new javax.swing.JCheckBox();
        jFemale = new javax.swing.JCheckBox();
        jBack = new javax.swing.JButton();
        jDisp = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jRemove = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jRC1 = new javax.swing.JCheckBox();
        jRC2 = new javax.swing.JCheckBox();
        jRC3 = new javax.swing.JCheckBox();
        jRC4 = new javax.swing.JCheckBox();
        jRC5 = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jRTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jRC6 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Vaccine Recipient");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel2.setText("Full Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Date of birth:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setText("Sex:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("RecipientID:");

        jAdd.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jAdd.setText("ADD");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Address:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Pre-vaccination questionaire:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel8.setText("6, Do you have dermal fillers?");

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel9.setText("1, A you sick today?");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel10.setText("2, Have you ever received a dose of COVID-19 vaccine?");

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel11.setText("3, Have you ever had an allergic reaction to any vaccine before you will take an COVID-19 Vacctine ?");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel12.setText("4, Have you received another vaccine in the last 14 days?");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel13.setText("5, Have you had a possitive test for COVID-19 or has a doctor ever told you that you have COVID-19?");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel14.setText("Vaccination Certificate");

        buttonGroup2.add(jQY1);
        jQY1.setText("Yes");
        jQY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQY1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jQY2);
        jQY2.setText("Yes");

        buttonGroup4.add(jQY3);
        jQY3.setText("Yes");
        jQY3.setToolTipText("");

        buttonGroup5.add(jQY4);
        jQY4.setText("Yes");

        buttonGroup6.add(jQY5);
        jQY5.setText("Yes");

        buttonGroup7.add(jQY6);
        jQY6.setText("Yes");

        buttonGroup2.add(jQN1);
        jQN1.setText("No");

        buttonGroup3.add(jQN2);
        jQN2.setText("No");
        jQN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQN2ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jQN3);
        jQN3.setText("No");

        buttonGroup5.add(jQN4);
        jQN4.setText("No");

        buttonGroup6.add(jQN5);
        jQN5.setText("No");

        buttonGroup7.add(jQN6);
        jQN6.setText("No");

        jRecepientID.setEditable(false);

        buttonGroup1.add(jMale);
        jMale.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jMale.setText("Male");
        jMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jFemale);
        jFemale.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jFemale.setText("Female");
        jFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFemaleActionPerformed(evt);
            }
        });

        jBack.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jBack.setText("BACK");
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });

        jDisp.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jDisp.setText("Display All");
        jDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDispActionPerformed(evt);
            }
        });

        jUpdate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jUpdate.setText("UPDATE");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jRemove.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jRemove.setText("REMOVE");
        jRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel18.setText("Pfizer-BioNTech");
        jLabel18.setToolTipText("");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel19.setText("Moderna");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel20.setText("Johnson & Johnson's Janssen");

        jLabel15.setText("1st Dose");

        jLabel16.setText("2nd Dose");

        buttonGroup8.add(jRC1);
        jRC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRC1ActionPerformed(evt);
            }
        });

        buttonGroup8.add(jRC2);

        buttonGroup8.add(jRC3);

        buttonGroup8.add(jRC4);

        buttonGroup8.add(jRC5);

        jRTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Recipient ID", "Full Name", "DateOfBirth", "Sex", "Address", "Question 1", "Question 2", "Question 3", "Question 4", "Question 5", "Question 6", "Vaccine certificate", "Number of Dose"
            }
        ));
        jRTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jRTable);

        jLabel21.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel21.setText("N/A");

        buttonGroup8.add(jRC6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.GREEN);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRC6))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRC3))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRC1))
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRC5)))
                                        .addGap(94, 94, 94)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRC4)
                                            .addComponent(jRC2)
                                            .addComponent(jLabel16))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jQY6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jQN6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jQY5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jQN5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRecepientID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jQY1)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jQY2))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jQY4))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jQY3))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jQN1)
                                            .addComponent(jQN2)
                                            .addComponent(jQN3)
                                            .addComponent(jQN4)))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jMale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jFemale))
                                            .addComponent(jFullName)
                                            .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(446, 446, 446))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRecepientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jMale)
                    .addComponent(jFemale)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jQY1)
                    .addComponent(jQN1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jQY2)
                    .addComponent(jQN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jQY3)
                    .addComponent(jQN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jQY4)
                    .addComponent(jQN4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jQY5)
                    .addComponent(jQN5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jQY6)
                    .addComponent(jQN6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jRC1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jRC3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRC2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRC4)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jRC5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUpdate)
                            .addComponent(jRemove)
                            .addComponent(jDisp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBack)
                        .addGap(192, 192, 192))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRC6)
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jQY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQY1ActionPerformed

    private void jFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFemaleActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
   this.setVisible(false);
   new AdminstratorForm().setVisible(true);
   new AdminstratorForm().setState(java.awt.Frame.NORMAL); 
   new AdminstratorForm().setSize(1600,900);
   new AdminstratorForm().setLocation(100, 100);   
    }//GEN-LAST:event_jBackActionPerformed

    private void jDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDispActionPerformed
       adminList.RList.display();
       
    }//GEN-LAST:event_jDispActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        addChange();
        if (jFullName.getText().equals("")||jDateBirth.getText().equals("")||sex.equals("")|| jAddress.getText().equals("")||Q1.equals("")||Q2.equals("")||Q3.equals("")||Q4.equals("")||Q5.equals("")||Q6.equals(""))
        infoBox("Please filling out your information", "Missing data");
        else
        {
           
            DefaultTableModel model = (DefaultTableModel)jRTable.getModel();
            if (model.getRowCount()>0){
           int  tempNum = Integer.parseInt(model.getValueAt(model.getRowCount()-1, 0).toString().substring(1));
          
        adminList.recipientIdNum=tempNum+1;
           }
           else 
               adminList.recipientIdNum++;
        adminList.RList.addRecipient("R"+String.valueOf(adminList.recipientIdNum), jFullName.getText(), jDateBirth.getText(),sex, jAddress.getText(),Q1,Q2,Q3,Q4,Q5,Q6,preCDose,numDose);
        adminList.RList.display();
        clearTable();
        }
        
    }//GEN-LAST:event_jAddActionPerformed
private void clearTable(){
        jRecepientID.setText("");
        jFullName.setText("");
        jDateBirth.setText("");
        jAddress.setText("");
        sex="";
        Q1="";
        Q2="";
        Q3="";
        Q4="";
        Q5="";
        Q6="";
        Q7="";
        preCDose=""; 
        numDose="";
        
        
        
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        buttonGroup8.clearSelection();
}
    private void jRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveActionPerformed
       if (adminList.RList.size()==0)
           infoBox("Please filling out your information", "Missing data");
       else 
       {
        adminList.RList.removeRecipient(jRecepientID.getText());
     adminList.RList.display();
       clearTable();}
    }//GEN-LAST:event_jRemoveActionPerformed

    private void jMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMaleActionPerformed

    private void jQN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQN2ActionPerformed

    private void jRC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRC1ActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
       addChange();
       if (adminList.RList.size()==0||jFullName.getText().equals("")||jDateBirth.getText().equals("")||sex.equals("")|| jAddress.getText().equals("")||Q1.equals("")||Q2.equals("")||Q3.equals("")||Q4.equals("")||Q5.equals("")||Q6.equals(""))
        infoBox("Please filling out your information", "Missing data");
       else{
       adminList.RList.updateRecipient(jRecepientID.getText(),jRecepientID.getText(), jFullName.getText(), jDateBirth.getText(),sex, jAddress.getText(),Q1,Q2,Q3,Q4,Q5,Q6,preCDose,numDose);
       adminList.RList.display();
    }
     clearTable();
    }//GEN-LAST:event_jUpdateActionPerformed
public void addChange(){
if (jMale.isSelected())
           sex = jMale.getText();
        else 
            if (jFemale.isSelected())
             sex = jFemale.getText();

if (jQY1.isSelected())
           Q1 = jQY1.getText();
        else 
            if (jQN1.isSelected())
             Q1 = jQN1.getText();
        if (jQY2.isSelected())
           Q2 = jQY2.getText();
        else 
            if (jQN2.isSelected())
             Q2 = jQN2.getText();
        if (jQY3.isSelected())
           Q3 = jQY3.getText();
        else 
            if (jQN3.isSelected())
             Q3 = jQN3.getText();
        if (jQY4.isSelected())
           Q4 = jQY4.getText();
        else 
            if (jQN4.isSelected())
             Q4 = jQN4.getText();
        if (jQY5.isSelected())
           Q5 = jQY5.getText();
        else 
            if (jQN5.isSelected())
             Q5 = jQN5.getText();
        if (jQY6.isSelected())
           Q6 = jQY6.getText();
        else 
            if (jQN5.isSelected())
             Q6 = jQN5.getText();
        if (jRC1.isSelected()){
           preCDose = "Pfizer-BioNTech" ;
            numDose = "1";}
        else 
            if (jRC2.isSelected()){
              preCDose = "Pfizer-BioNTech" ;
            numDose = "2";}
        else 
            if (jRC3.isSelected()){
              preCDose = "Moderna" ;
            numDose = "1";}
        else 
            if (jRC4.isSelected()){
              preCDose = "Moderna" ;
            numDose = "2";}
        else 
            if (jRC5.isSelected()){
              preCDose = "Johnson & Johnson's Janssen" ;
            numDose = "1";}
            else if (jRC6.isSelected()){
            preCDose = "N/A" ;
            numDose = "N/A";}
            else {
                preCDose = "N/A" ;
            numDose = "N/A";
            }
};
    private void jRTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRTableMouseClicked
       DefaultTableModel model = (DefaultTableModel) jRTable.getModel();
       int selectedRowIndex = jRTable.getSelectedRow();
       jRecepientID.setText(model.getValueAt(selectedRowIndex,0).toString());
       jFullName.setText(model.getValueAt(selectedRowIndex,1).toString());
       jDateBirth.setText(model.getValueAt(selectedRowIndex,2).toString());
       jAddress.setText(model.getValueAt(selectedRowIndex,4).toString());
     sex=model.getValueAt(selectedRowIndex,3).toString();
       if (sex.equals("Male"))
           jMale.setSelected(true);
        else 
            if (sex.equals("Female"))
           jFemale.setSelected(true);
       
       Q1=model.getValueAt(selectedRowIndex,5).toString();
        if (Q1.equals("Yes"))
           jQY1.setSelected(true);
        else 
            if (Q1.equals("No"))
           jQN1.setSelected(true);
       Q2=model.getValueAt(selectedRowIndex,6).toString();
        if (Q2.equals("Yes"))
           jQY2.setSelected(true);
        else 
            if (Q2.equals("No"))
           jQN2.setSelected(true);
        Q3=model.getValueAt(selectedRowIndex,7).toString();
        if (Q3.equals("Yes"))
           jQY3.setSelected(true);
        else 
            if (Q3.equals("No"))
           jQN3.setSelected(true);
        Q4=model.getValueAt(selectedRowIndex,8).toString();
        if (Q4.equals("Yes"))
           jQY4.setSelected(true);
        else 
            if (Q4.equals("No"))
           jQN4.setSelected(true);
        Q5=model.getValueAt(selectedRowIndex,9).toString();
        if (Q5.equals("Yes"))
           jQY5.setSelected(true);
        else 
            if (Q5.equals("No"))
           jQN5.setSelected(true);
        Q6=model.getValueAt(selectedRowIndex,10).toString();
        if (Q6.equals("Yes"))
           jQY6.setSelected(true);
        else 
            if (Q6.equals("No"))
           jQN6.setSelected(true);
       preCDose=model.getValueAt(selectedRowIndex,11).toString();
       numDose=model.getValueAt(selectedRowIndex,12).toString();
        if (preCDose.equals("Pfizer-BioNTech") && numDose.equals("1")){
 
        jRC1.setSelected(true);
        }
        else 
            if (preCDose.equals("Pfizer-BioNTech") && numDose.equals("2")){
 
        jRC2.setSelected(true);
        }
        else 
           if (preCDose.equals("Moderna") && numDose.equals("1")){
 
        jRC3.setSelected(true);
        }
        else 
            if (preCDose.equals("Moderna") && numDose.equals("2")){
 
        jRC4.setSelected(true);
        }
        else 
            if (preCDose.equals("Johnson & Johnson's Janssen") && numDose.equals("1")){
    jRC5.setSelected(true);
    }//GEN-LAST:event_jRTableMouseClicked
    else 
            if (preCDose.equals("N/A") && numDose.equals("N/A")){
    jRC6.setSelected(true);
    }    
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        adminList.RList.display();
    }//GEN-LAST:event_formWindowOpened

    
    


    public static void infoBox(String infoMessage, String titleBar)
    {   
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

    
    public static void main(String args[]) {

        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipientForm().setVisible(true);
            }
        });
    }
   
    private String sex="";    
    private String Q1="";
    private String Q2="";
    private String Q3="";
    private String Q4="";
    private String Q5="";
    private String Q6="";
    private String Q7="";
    private String preCDose="";
    private String numDose="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jAdd;
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jBack;
    private javax.swing.JTextField jDateBirth;
    private javax.swing.JButton jDisp;
    private javax.swing.JCheckBox jFemale;
    private javax.swing.JTextField jFullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jMale;
    private javax.swing.JCheckBox jQN1;
    private javax.swing.JCheckBox jQN2;
    private javax.swing.JCheckBox jQN3;
    private javax.swing.JCheckBox jQN4;
    private javax.swing.JCheckBox jQN5;
    private javax.swing.JCheckBox jQN6;
    private javax.swing.JCheckBox jQY1;
    private javax.swing.JCheckBox jQY2;
    private javax.swing.JCheckBox jQY3;
    private javax.swing.JCheckBox jQY4;
    private javax.swing.JCheckBox jQY5;
    private javax.swing.JCheckBox jQY6;
    private javax.swing.JCheckBox jRC1;
    private javax.swing.JCheckBox jRC2;
    private javax.swing.JCheckBox jRC3;
    private javax.swing.JCheckBox jRC4;
    private javax.swing.JCheckBox jRC5;
    private javax.swing.JCheckBox jRC6;
    public static javax.swing.JTable jRTable;
    private javax.swing.JTextField jRecepientID;
    private javax.swing.JButton jRemove;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables
}
